// ==========================================================
// BELGIN KUYUMCULUK — LÜKS SAAT & MÜCEVHERAT (EST. 1999)
// %100 GERÇEK VE SERTİFİKALI KOLEKSİYON VERİTABANI
// ==========================================================

const WATCH_BRANDS = [
  { name: "TAG Heuer", slug: "tag-heuer", count: "12 Model", image: "https://artjewellerywatches.com/api/photo/site/tile.wbrand.rolex" },
  { name: "Longines", slug: "longines", count: "8 Model", image: "https://artjewellerywatches.com/api/photo/site/tile.wbrand.patek" },
  { name: "Rado", slug: "rado", count: "6 Model", image: "https://artjewellerywatches.com/api/photo/site/tile.wbrand.ap" },
  { name: "Cartier", slug: "cartier", count: "10 Model", image: "https://artjewellerywatches.com/api/photo/site/tile.wbrand.cartier" },
  { name: "Rolex", slug: "rolex", count: "5 Model", image: "https://artjewellerywatches.com/api/photo/site/tile.wbrand.iwc" }
];

const JEWELRY_BRANDS = [
  { name: "Cartier", slug: "cartier", count: "14 Parça", image: "https://artjewellerywatches.com/api/photo/site/tile.jbrand.cartier" },
  { name: "Tiffany & Co.", slug: "tiffany-co", count: "9 Parça", image: "https://artjewellerywatches.com/api/photo/site/tile.jbrand.tiffany" },
  { name: "Bvlgari", slug: "bulgari", count: "11 Parça", image: "https://artjewellerywatches.com/api/photo/site/tile.jbrand.bulgari" },
  { name: "Van Cleef & Arpels", slug: "vancleef", count: "8 Parça", image: "https://artjewellerywatches.com/api/photo/site/tile.jbrand.vancleef" },
  { name: "Chopard", slug: "chopard", count: "6 Parça", image: "https://artjewellerywatches.com/api/photo/site/tile.jbrand.other" }
];

const PRODUCTS = [
  // ==========================================
  // 1. İKİNCİ EL SAATLER (TAG HEUER, LONGINES, RADO)
  // ==========================================
  {
    id: 101,
    brand: "TAG Heuer",
    name: "Carrera Date Twin-Time GMT",
    reference: "WDA2114.BA0043 · 41mm",
    category: "watch",
    statusBadge: "Stokta",
    conditionBadge: "İkinci El",
    isPreOwned: true,
    isGold: false,
    price: 292500,
    metal: "Paslanmaz Çelik 316L",
    dial: "Güneş Işını Teal Yeşili Kadran & Çift Zaman GMT",
    year: "2024",
    boxPapers: "Orijinal Kutu & Uluslararası Garanti Kartı",
    desc: "TAG Heuer Carrera Date Twin-Time ref. WDA2114; 41mm paslanmaz çelik kasa, otomatik Calibre 7 Twin-Time mekanizma, 80 saat güç rezervi, safir kristal cam ve 100m su geçirmezlik.",
    image: "https://artjewellerywatches.com/api/photo/watch-definition/685",
    hoverImage: "https://artjewellerywatches.com/api/photo/watch-definition/685",
    amplitude: "290° (Swiss Chronometer)",
    rateAccuracy: "+1.2 sn/gün",
    waterTest: "10 Bar (100 Metre) Geçti",
    inStock: true
  },
  {
    id: 102,
    brand: "TAG Heuer",
    name: "Carrera Chronograph Otomatik",
    reference: "CBN2A1AA.FT6228 · 44mm",
    category: "watch",
    statusBadge: "Stokta",
    conditionBadge: "İkinci El",
    isPreOwned: true,
    isGold: false,
    price: 255000,
    metal: "Paslanmaz Çelik & Seramik Takimetre Bezel",
    dial: "Siyah Kadran & Kırmızı Kronograf İbreleri",
    year: "2023",
    boxPapers: "Orijinal Kutu & Garanti Belgesi",
    desc: "TAG Heuer Carrera Chronograph 44mm; Calibre Heuer 02 / Calibre 16 otomatik kronograf mekanizma, siyah seramik takimetre bezel, perfore kauçuk yarış kordonu ve 100m su geçirmezlik.",
    image: "https://artjewellerywatches.com/api/photo/watch-definition/672",
    hoverImage: "https://artjewellerywatches.com/api/photo/watch-definition/672",
    amplitude: "288° (Heuer Kalibrasyonu)",
    rateAccuracy: "+1.5 sn/gün",
    waterTest: "10 Bar (100 Metre) Geçti",
    inStock: true
  },
  {
    id: 103,
    brand: "TAG Heuer",
    name: "Formula 1 Chronograph Gulf Edition",
    reference: "CAZ101N.FC8243 · 43mm",
    category: "watch",
    statusBadge: "Stokta",
    conditionBadge: "İkinci El",
    isPreOwned: true,
    isGold: false,
    price: 135000,
    metal: "Paslanmaz Çelik & Mavi Alüminyum Takimetre Bezel",
    dial: "Gulf Yarış Şeritli Güneş Işını Mavi Kadran",
    year: "2023",
    boxPapers: "Gulf Özel Seri Kutu & Garanti Kartı",
    desc: "TAG Heuer Formula 1 Gulf Special Edition; efsanevi açık mavi ve turuncu Gulf yarış çizgili kadran, 1/10 saniye hassasiyetli İsviçre kronograf kalibre, mavi deri yarış kayışı ve 200m su geçirmezlik.",
    image: "https://artjewellerywatches.com/api/photo/watch-definition/486",
    hoverImage: "https://artjewellerywatches.com/api/photo/watch-definition/486",
    amplitude: "Quartz 32.768 Hz Hassasiyet",
    rateAccuracy: "+0.1 sn/ay",
    waterTest: "20 Bar (200 Metre) Geçti",
    inStock: true
  },
  {
    id: 104,
    brand: "TAG Heuer",
    name: "Formula 1 Date Siyah 41mm",
    reference: "WAZ1110.FT8023 · 41mm",
    category: "watch",
    statusBadge: "Stokta",
    conditionBadge: "İkinci El",
    isPreOwned: true,
    isGold: false,
    price: 105000,
    metal: "İnce Fırçalanmış Çelik & Titanyum Karbür Bezel",
    dial: "Opalin Siyah Kadran & Luminesan İndeksler",
    year: "2024",
    boxPapers: "Orijinal Kutu ve Evrakları Eksiksiz",
    desc: "TAG Heuer Formula 1 ref. WAZ1110; 41mm çelik kasa, tek yönlü döner titanyum karbür kaplama siyah bezel, dayanıklı kauçuk kayış ve 200m dalgıç sınıfı su geçirmezlik.",
    image: "https://artjewellerywatches.com/api/photo/watch-definition/637",
    hoverImage: "https://artjewellerywatches.com/api/photo/watch-definition/637",
    amplitude: "İsviçre Hassas Kuvars",
    rateAccuracy: "+0.2 sn/ay",
    waterTest: "20 Bar (200 Metre) Geçti",
    inStock: true
  },
  {
    id: 105,
    brand: "Longines",
    name: "HydroConquest Otomatik Seramik",
    reference: "L3.781.4.56.6 · 41mm",
    category: "watch",
    statusBadge: "Stokta",
    conditionBadge: "İkinci El",
    isPreOwned: true,
    isGold: false,
    price: 78500,
    metal: "Paslanmaz Çelik & Çizilmez Siyah Seramik Bezel",
    dial: "Güneş Işını Siyah Kadran",
    year: "2023",
    boxPapers: "Longines Ahşap Kutu & Uluslararası Garanti Kartı",
    desc: "Longines HydroConquest L3.781.4.56.6; 41mm çelik kasa, tek yönlü döner siyah seramik bezel, otomatik kalibre L888 (72 saat güç rezervi, silikon denge yayı) ve 300m profesyonel dalgıç dayanıklılığı.",
    image: "https://artjewellerywatches.com/api/photo/watch-definition/660",
    hoverImage: "https://artjewellerywatches.com/api/photo/watch-definition/660",
    amplitude: "292° (Kalibre L888 Standartı)",
    rateAccuracy: "+1.1 sn/gün",
    waterTest: "30 Bar (300 Metre) Geçti",
    inStock: true
  },
  {
    id: 106,
    brand: "Longines",
    name: "Master Collection Moonphase Ay Fazı",
    reference: "L2.909.4.78.3 · 40mm",
    category: "watch",
    statusBadge: "Stokta",
    conditionBadge: "İkinci El",
    isPreOwned: true,
    isGold: false,
    price: 152000,
    metal: "Paslanmaz Çelik & Kahverengi Timsah Deri Kayış",
    dial: "Gümüş Arpa Tanesi Kadran & Mavileştirilmiş Çelik Kollar",
    year: "2024",
    boxPapers: "Longines Özel Kutu & Ay Fazı Garanti Belgesi",
    desc: "The Longines Master Collection L2.909; klasik gümüş arpa deseni kadran, saat 6 konumunda ay fazı ve tarih göstergesi, safir arka kapak ve 72 saat rezervli otomatik kalibre L899.",
    image: "https://artjewellerywatches.com/api/photo/watch-definition/549",
    hoverImage: "https://artjewellerywatches.com/api/photo/watch-definition/549",
    amplitude: "296° (İsviçre Üst Segment)",
    rateAccuracy: "+0.7 sn/gün",
    waterTest: "3 Bar (30 Metre) Geçti",
    inStock: true
  },
  {
    id: 107,
    brand: "Rado",
    name: "Captain Cook Otomatik Yeşil Seramik",
    reference: "R32105353 · 42mm",
    category: "watch",
    statusBadge: "Stokta",
    conditionBadge: "İkinci El",
    isPreOwned: true,
    isGold: false,
    price: 143500,
    metal: "Paslanmaz Çelik & Yüksek Teknoloji Yeşil Seramik Bezel",
    dial: "Güneş Işını Zümrüt Yeşili Kadran & Hareketli Çapa",
    year: "2024",
    boxPapers: "Rado Deri Seyahat Çantası & Kutu / Evrak",
    desc: "Rado Captain Cook ref. R32105353; 42mm çelik kasa, çizilmez yeşil seramik döner bezel, EasyClip pirinç tanesi çelik bilezik, 80 saat güç rezervli Rado kalibre R763 ve 300m su geçirmezlik.",
    image: "https://artjewellerywatches.com/api/photo/watch-definition/298",
    hoverImage: "https://artjewellerywatches.com/api/photo/watch-definition/298",
    amplitude: "294° (Nivachron™ Anti-Manyetik)",
    rateAccuracy: "+0.9 sn/gün",
    waterTest: "30 Bar (300 Metre) Geçti",
    inStock: true
  },
  {
    id: 108,
    brand: "Rado",
    name: "True Square İskelet Otomatik",
    reference: "R27086162 · 38mm",
    category: "watch",
    statusBadge: "Stokta",
    conditionBadge: "İkinci El",
    isPreOwned: true,
    isGold: false,
    price: 138000,
    metal: "Monoblok Yüksek Teknoloji Parlak Siyah Seramik",
    dial: "Açık Mekanizma İskelet Kadran & Altın Detaylar",
    year: "2023",
    boxPapers: "Rado Orijinal Kutu & Garanti Kartı",
    desc: "Rado True Square ref. R27086162; monoblok enjeksiyon kalıplı hafif ve ultra dayanıklı yüksek teknoloji parlak siyah seramik kare kasa, 80 saat güç rezervli iskeletleştirilmiş otomatik mekanizma.",
    image: "https://artjewellerywatches.com/api/photo/watch-definition/575",
    hoverImage: "https://artjewellerywatches.com/api/photo/watch-definition/575",
    amplitude: "289° (Rado Kalibre R734)",
    rateAccuracy: "+1.4 sn/gün",
    waterTest: "5 Bar (50 Metre) Geçti",
    inStock: true
  },

  // ==========================================
  // 2. MÜCEVHERLER & İKİNCİ EL MASİF ALTIN
  // ==========================================
  {
    id: 1,
    brand: "Cartier",
    name: "Juste un Clou Pırlantalı Bilezik",
    reference: "B6065818 · 18",
    category: "jewelry",
    statusBadge: "Stokta",
    conditionBadge: "İkinci El",
    isPreOwned: true,
    isGold: true,
    price: 490000,
    metal: "18K Sarı Altın (Au750)",
    dial: "0.58 ct Pavé Pırlantalar",
    year: "2024",
    boxPapers: "Cartier Kırmızı Kutu & Sertifika",
    desc: "Cartier Juste un Clou B6065818; 18 ayar sarı altın gövde üzerinde 32 adet parlak kesim pırlanta bezeli çivi formlu lüks kelepçe.",
    image: "https://artjewellerywatches.com/api/photo/jewelry-definition/100",
    hoverImage: "https://artjewellerywatches.com/api/photo/jewelry-definition/100",
    hallmark: "Au750 • Cartier 18 • Seri No Lazerli",
    inStock: true
  },
  {
    id: 2,
    brand: "Tiffany & Co.",
    name: "Setting Tektaş Pırlanta Yüzük",
    reference: "70524805 · 11",
    category: "jewelry",
    statusBadge: "Stokta",
    conditionBadge: "İkinci El",
    isPreOwned: true,
    isGold: false,
    price: 780000,
    metal: "950 Masif Platin (Pt950)",
    dial: "1.50 ct D-VVS1 Doğal Pırlanta",
    year: "2023",
    boxPapers: "Tiffany Mavi Kutu & GIA Sertifikası",
    desc: "Tiffany & Co. Setting 6 tırnaklı platin pırlanta yüzük; 1.50 karat D renk VVS1 berraklığında doğal elmas, GIA lazer yazılı sertifikalı tescil.",
    image: "https://artjewellerywatches.com/api/photo/jewelry-definition/20",
    hoverImage: "https://artjewellerywatches.com/api/photo/jewelry-definition/20",
    hallmark: "PT950 • Tiffany&Co. • GIA-55421099",
    inStock: true
  },
  {
    id: 3,
    brand: "Cartier",
    name: "Love Bilezik Klasik Rose Altın",
    reference: "B6070117 · 17",
    category: "jewelry",
    statusBadge: "Stokta",
    conditionBadge: "İkinci El",
    isPreOwned: true,
    isGold: true,
    price: 375000,
    metal: "18K Rose Altın (Au750)",
    dial: "Klasik Vida Motifleri",
    year: "2024",
    boxPapers: "Orijinal Tornavida & Cartier Kutu",
    desc: "Cartier Love B6070117 klasik model; 18 ayar rose pembe altın gövde, vidalı açma-kapama sistemi ve ergonomik oval bilek formu.",
    image: "https://artjewellerywatches.com/api/photo/jewelry-definition/95",
    hoverImage: "https://artjewellerywatches.com/api/photo/jewelry-definition/95",
    hallmark: "Au750 • 17 • CRD99218",
    inStock: true
  },
  {
    id: 4,
    brand: "Cartier",
    name: "Love Bilezik Klasik Sarı Altın",
    reference: "B6067417 · 18",
    category: "jewelry",
    statusBadge: "Stokta",
    conditionBadge: "İkinci El",
    isPreOwned: true,
    isGold: true,
    price: 365000,
    metal: "18K Sarı Altın (Au750)",
    dial: "Klasik Vida Motifleri",
    year: "2023",
    boxPapers: "Kutu ve Orijinal Tornavida",
    desc: "Cartier Love B6067417; 18 ayar sarı altın klasik kelepçe bilezik.",
    image: "https://artjewellerywatches.com/api/photo/jewelry-definition/36",
    hoverImage: "https://artjewellerywatches.com/api/photo/jewelry-definition/36",
    hallmark: "Au750 • 18 • CKR44120",
    inStock: true
  },
  {
    id: 5,
    brand: "Cartier",
    name: "Love Yüzük Küçük Sarı Altın",
    reference: "B4085000 · 56",
    category: "jewelry",
    statusBadge: "Stokta",
    conditionBadge: "İkinci El",
    isPreOwned: true,
    isGold: true,
    price: 95000,
    metal: "18K Sarı Altın (Au750)",
    dial: "Vida Motifli Küçük Boy",
    year: "2024",
    boxPapers: "Cartier Kutu & Garanti Belgesi",
    desc: "Cartier Love küçük model yüzük; 18 ayar sarı altın, 3.6mm genişlik.",
    image: "https://artjewellerywatches.com/api/photo/jewelry-definition/85",
    hoverImage: "https://artjewellerywatches.com/api/photo/jewelry-definition/85",
    hallmark: "Au750 • 56",
    inStock: true
  },
  {
    id: 6,
    brand: "Cartier",
    name: "Juste un Clou Klasik Sarı Altın",
    reference: "B6048617 · 16",
    category: "jewelry",
    statusBadge: "Stokta",
    conditionBadge: "Sıfır",
    isPreOwned: false,
    isGold: true,
    price: 430000,
    metal: "18K Sarı Altın (Au750)",
    dial: "Pırlantasız Klasik Model",
    year: "2026",
    boxPapers: "Sıfır Kutusunda & Sertifikalı",
    desc: "Cartier Juste un Clou klasik sarı altın bilezik.",
    image: "https://artjewellerywatches.com/api/photo/jewelry-definition/29",
    hoverImage: "https://artjewellerywatches.com/api/photo/jewelry-definition/29",
    hallmark: "Au750 • 16 • Sıfır Mühür",
    inStock: true
  },
  {
    id: 7,
    brand: "Cartier",
    name: "Love Bilezik Klasik Beyaz Altın",
    reference: "B6070017 · 16",
    category: "jewelry",
    statusBadge: "Stokta",
    conditionBadge: "İkinci El",
    isPreOwned: true,
    isGold: true,
    price: 390000,
    metal: "18K Beyaz Altın (Au750)",
    dial: "Rodyum Kaplama Beyaz Altın",
    year: "2024",
    boxPapers: "Orijinal Kutu ve Tornavida",
    desc: "Cartier Love B6070017 beyaz altın kelepçe bilezik; 18 ayar beyaz altın, rodyum kaplama parıltısı.",
    image: "https://artjewellerywatches.com/api/photo/jewelry-definition/87",
    hoverImage: "https://artjewellerywatches.com/api/photo/jewelry-definition/87",
    hallmark: "Au750 • 16 • Cartier Beyaz",
    inStock: true
  },
  {
    id: 8,
    brand: "Cartier",
    name: "Juste un Clou Yüzük Sarı Altın",
    reference: "B4092600 · 54",
    category: "jewelry",
    statusBadge: "Stokta",
    conditionBadge: "İkinci El",
    isPreOwned: true,
    isGold: true,
    price: 110000,
    metal: "18K Sarı Altın (Au750)",
    dial: "Çivi Motifli Klasik Boy",
    year: "2023",
    boxPapers: "Cartier Kutu & Sertifika",
    desc: "Cartier Juste un Clou sarı altın çivi yüzük; 18 ayar sarı altın, ikonik tasarım.",
    image: "https://artjewellerywatches.com/api/photo/jewelry-definition/33",
    hoverImage: "https://artjewellerywatches.com/api/photo/jewelry-definition/33",
    hallmark: "Au750 • 54 • JUC901",
    inStock: true
  }
];

const WATCHES = PRODUCTS.filter(p => p.category === "watch");
const JEWELLERY = PRODUCTS.filter(p => p.category === "jewelry");
const PRE_OWNED_ITEMS = PRODUCTS.filter(p => p.isPreOwned);
const PRE_OWNED_GOLD = PRODUCTS.filter(p => p.isPreOwned && p.isGold);

const CERTIFICATE_DB = {
  "WDA2114": { brand: "TAG Heuer", model: "Carrera Date Twin-Time", authStatus: "%100 Orijinal Tescilli", certNo: "TAG-WDA-2114", expert: "İzmir Kuyumcular Odası Tescilli Ekspertiz" },
  "CBN2A1AA": { brand: "TAG Heuer", model: "Carrera Chronograph 44mm", authStatus: "%100 Orijinal Tescilli", certNo: "TAG-CBN-0643", expert: "İzmir Kuyumcular Odası Tescilli Ekspertiz" },
  "CAZ101N": { brand: "TAG Heuer", model: "Formula 1 Gulf Edition", authStatus: "%100 Orijinal Tescilli", certNo: "TAG-CAZ-8243", expert: "İzmir Kuyumcular Odası Tescilli Ekspertiz" },
  "WAZ1110": { brand: "TAG Heuer", model: "Formula 1 Date 41mm", authStatus: "%100 Orijinal Tescilli", certNo: "TAG-WAZ-8023", expert: "İzmir Kuyumcular Odası Tescilli Ekspertiz" },
  "L3.781.4": { brand: "Longines", model: "HydroConquest Seramik 41mm", authStatus: "%100 Orijinal Tescilli", certNo: "LNG-3781-566", expert: "İzmir Kuyumcular Odası Tescilli Ekspertiz" },
  "L2.909.4": { brand: "Longines", model: "Master Collection Moonphase", authStatus: "%100 Orijinal Tescilli", certNo: "LNG-2909-783", expert: "İzmir Kuyumcular Odası Tescilli Ekspertiz" },
  "R32105353": { brand: "Rado", model: "Captain Cook Yeşil Seramik", authStatus: "%100 Orijinal Tescilli", certNo: "RDO-3210-5353", expert: "İzmir Kuyumcular Odası Tescilli Ekspertiz" },
  "R27086162": { brand: "Rado", model: "True Square İskelet", authStatus: "%100 Orijinal Tescilli", certNo: "RDO-2708-6162", expert: "İzmir Kuyumcular Odası Tescilli Ekspertiz" },
  "B6065818": { brand: "Cartier", model: "Juste un Clou Pırlantalı", authStatus: "%100 Orijinal Tescilli", certNo: "CRT-JUC-3301", expert: "GIA Sertifikalı Gemolog İncelemesi" },
  "70524805": { brand: "Tiffany & Co.", model: "Setting 1.50ct Tektaş", authStatus: "%100 Orijinal Tescilli", certNo: "GIA-55421099", expert: "GIA Uluslararası Elmas Raporu" }
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    PRODUCTS,
    WATCH_BRANDS,
    JEWELRY_BRANDS,
    WATCHES,
    JEWELLERY,
    PRE_OWNED_ITEMS,
    PRE_OWNED_GOLD,
    CERTIFICATE_DB
  };
}
